### ISSUE TITLE
Creating new root item

### ISSUE THREAD

**Issue by ccastillop** [svenfuchs/simple_nested_set#6]
With :mysql or :mysql2 driver and with path and level fields....

  ruby-1.8.7-p299 > s = Seccion.new

   => #<Seccion id: nil, nombre: nil, parent_id: nil, lft: nil, rgt: nil, created_at: nil, updated_at: nil, path: nil, level: nil> 

  ruby-1.8.7-p299 > s.nombre = "Quienes Somos"

   => "Quienes Somos" 

  ruby-1.8.7-p299 > s.save

  ActiveRecord::StatementInvalid: Mysql::Error: You can't specify target table 'secciones' for update in FROM clause: UPDATE `secciones` SET level = (SELECT     count(id) FROM       `secciones` `l`  WHERE     `l`.`lft` < `secciones`.`lft` AND `l`.`rgt` > `secciones`.`rgt`),path = (SELECT     GROUP_CONCAT(`slug`, '/') FROM       `secciones` `l`  WHERE     `l`.`lft` <= `secciones`.`lft` AND `l`.`rgt` >= `secciones`.`rgt`)

**Comment by kronn** [comment]
Thanks for the info, I will investigate. Both concrete solutions and pull requests are highly appreciated. ;)

I think I have to also extend the CI-setup so that such errors don't crawl up again.

Which MySQL-version do you use?

**Comment by ccastillop** [comment]
mysql  Ver 14.14 Distrib 5.1.49, for apple-darwin10.3.0 (i386) using readline 5.1
Rails 3.0.1

**Comment by kronn** [comment]
Okay, I can now reproduce this one. Postgresql and Sqlite work fine, though.
I'll have to dig a little on a workaround.

This has to be fixed, sure. May I still suggest switching to Postgres? ;)

**Comment by kronn** [comment]
okay, i managed to work around this problem, but some tests still fail on mysql. I think that I have some more work to do in order to port this to mysql.

**Comment by kronn** [comment]
sorry that this took so long, but mysql needs a whole different approach to some after-save denormalizations.

We just release version 0.1.0 which runs on PostgreSQL, SQLite and MySQL. All three databases are used in tests so we don't break anything in the future. 

Thanks a lot for this bugreport!
