### ISSUE TITLE
#self_and_* methods should return a scope

### ISSUE THREAD

**Issue by levinalex** [svenfuchs/simple_nested_set#7]
the method `self_and_ancestors` is implemented as:

```
[self] + ancestors
```

therefore it does not return a scope as `ancestors` does but forces evaluation and returns an Array.

would you consider accepting a patch that changes the behavior of these methods to return a scope?

**Comment by svenfuchs** [comment]
sure, i absolutely would. :)

**Comment by levinalex** [comment]
see #8
